project_id = "itcnukhlqkrsirrznuig"

[functions.translate-quiz]
verify_jwt = true

[functions.suggest-headline]
verify_jwt = true

[functions.generate-results]
verify_jwt = true

[functions.fill-result-level]
verify_jwt = true

[functions.sync-answer-weights]
verify_jwt = true

[functions.suggest-tone]
verify_jwt = true

[functions.extract-from-url]
verify_jwt = true

[functions.generate-open-mindedness-results]
verify_jwt = true

[functions.translate-email-template]
verify_jwt = true

[functions.check-domain-reputation]
verify_jwt = true

[functions.translate-email-body]
verify_jwt = true

[functions.translate-web-results]
verify_jwt = true

[functions.translate-hypothesis-to-english]
verify_jwt = true

[functions.translate-cta]
verify_jwt = true

[functions.process-email-queue]
verify_jwt = false

[functions.send-quiz-results]
verify_jwt = false

[functions.send-hypothesis-admin-email]
verify_jwt = false

[functions.send-hypothesis-user-email]
verify_jwt = false

[functions.send-emotional-user-email]
verify_jwt = false

[functions.process-pending-emails]
verify_jwt = false

[functions.render-email-preview]
verify_jwt = true

[functions.pregenerate-email-preview]
verify_jwt = false

[functions.batch-translate-quizzes]
verify_jwt = true

[functions.translate-quiz-basics]
verify_jwt = true

[functions.translate-result-levels]
verify_jwt = false

[functions.translate-email-subjects]
verify_jwt = false
