project_id = "itcnukhlqkrsirrznuig"

[functions.import-email-logs]
verify_jwt = false

[functions.import-quiz-leads]
verify_jwt = false

[functions.translate-quiz]
verify_jwt = true

[functions.suggest-headline]
verify_jwt = true

[functions.generate-results]
verify_jwt = true

[functions.fill-result-level]
verify_jwt = true

[functions.sync-answer-weights]
verify_jwt = true

[functions.suggest-tone]
verify_jwt = true

[functions.extract-from-url]
verify_jwt = true

[functions.generate-open-mindedness-results]
verify_jwt = true

[functions.translate-email-template]
verify_jwt = true

[functions.check-domain-reputation]
verify_jwt = true

[functions.translate-email-body]
verify_jwt = true

[functions.translate-web-results]
verify_jwt = true
